/**
 * Auth Middleware V2 - OTP-Only Multi-Account
 * 
 * Validates access tokens generated by our backend (not Supabase)
 * No supabase_user_id anywhere
 */
const { verifyAccessToken } = require('../controllers/authControllerV2');

const authMiddleware = async (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ error: 'Missing or invalid authorization header' });
    }

    const token = authHeader.substring(7);
    const decoded = verifyAccessToken(token);

    if (!decoded) {
      return res.status(401).json({ error: 'Invalid or expired token' });
    }

    // decoded contains: { sub, userId, userType, email }
    const { userId, userType, email } = decoded;

    console.log('[Auth] Token validated:', { userId, userType, email });

    // Set user on request for downstream handlers
    req.user = {
      id: userId,
      type: userType,
      email: email,
    };

    next();
  } catch (err) {
    console.error('[Auth] Middleware error:', err.message);
    res.status(500).json({ error: 'Authentication failed' });
  }
};

module.exports = authMiddleware;
